issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
