version: '3.7'

services:
  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: realize start --run
    privileged: true
    ports:
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
