version: '3.7'

services:
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: realize start --run
    ports:
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=go:8888
  portfolio-backend-mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: portfolio_backend
      MYSQL_USER: nekochans
      MYSQL_PASSWORD: nekochans(Password2222)
      MYSQL_ROOT_PASSWORD: nekochans(Password2222)
    ports:
      - "63306:3306"
    volumes:
      - portfolio-backend-mysql-data:/var/lib/mysql
      - ./docker/mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql
volumes:
  portfolio-backend-mysql-data:
